#!/usr/bin/env python3
"""
Professional PDF Report Generation for net-inspect
Creates client-ready security assessment reports
"""

import json
from datetime import datetime
from typing import Dict, List, Any, Optional
from pathlib import Path

try:
    from reportlab.lib.pagesizes import letter, A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
        PageBreak, Image, KeepTogether
    )
    from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


class ProfessionalReport:
    """
    Generate professional PDF security reports.

    Report Sections:
    - Executive Summary
    - Network Topology
    - Risk Analysis
    - Vulnerability Findings
    - CVE Details
    - TLS/SSL Audit
    - Threat Intelligence
    - Recommendations
    """

    def __init__(self, scan_data: Dict[str, Any], report_format: str = 'professional'):
        """
        Initialize PDF Report Generator.

        Args:
            scan_data: Complete scan results
            report_format: Report style (executive, professional, technical)
        """
        if not REPORTLAB_AVAILABLE:
            raise ImportError("PDF reporting requires reportlab. Install with: pip install reportlab")

        self.scan_data = scan_data
        self.report_format = report_format
        self.styles = getSampleStyleSheet()

        # Custom styles
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a237e'),
            spaceAfter=30,
            alignment=TA_CENTER
        ))

        self.styles.add(ParagraphStyle(
            name='RiskCritical',
            parent=self.styles['Normal'],
            textColor=colors.red,
            fontName='Helvetica-Bold'
        ))

    def generate(self, output_file: str):
        """Generate PDF report."""
        doc = SimpleDocTemplate(
            output_file,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )

        story = []

        # Cover Page
        story.extend(self._create_cover_page())
        story.append(PageBreak())

        # Executive Summary
        story.extend(self._create_executive_summary())
        story.append(PageBreak())

        # Network Overview
        story.extend(self._create_network_overview())
        story.append(PageBreak())

        # Risk Analysis
        story.extend(self._create_risk_analysis())
        story.append(PageBreak())

        # Vulnerability Findings (includes ports, CVEs, exploits)
        story.extend(self._create_vulnerability_findings())
        story.append(PageBreak())

        # TLS/SSL Audit
        story.extend(self._create_tls_audit_section())
        story.append(PageBreak())

        # Threat Intelligence
        story.extend(self._create_threat_intel_section())
        story.append(PageBreak())

        # Traffic Analysis
        story.extend(self._create_traffic_analysis_section())
        story.append(PageBreak())

        # Recommendations
        story.extend(self._create_recommendations())

        # Build PDF
        doc.build(story)

    def _create_cover_page(self) -> List:
        """Create cover page."""
        story = []

        story.append(Spacer(1, 2*inch))

        # Title
        title = Paragraph(
            "Network Security Assessment Report",
            self.styles['CustomTitle']
        )
        story.append(title)

        story.append(Spacer(1, 0.5*inch))

        # Subtitle
        scan_id = self.scan_data.get('scan_id', 'UNKNOWN')
        timestamp = self.scan_data.get('timestamp', datetime.now().isoformat())

        subtitle_text = f"<font size=14><b>Scan ID:</b> {scan_id}<br/><b>Date:</b> {timestamp}</font>"
        subtitle = Paragraph(subtitle_text, self.styles['Normal'])
        story.append(subtitle)

        story.append(Spacer(1, 1*inch))

        # Generated by
        footer = Paragraph(
            "<font size=10>Generated by net-inspect v1.0.0<br/>Professional Network Security Intelligence Tool</font>",
            self.styles['Normal']
        )
        story.append(footer)

        return story

    def _create_executive_summary(self) -> List:
        """Create executive summary section."""
        story = []

        story.append(Paragraph("Executive Summary", self.styles['Heading1']))
        story.append(Spacer(1, 12))

        # Key metrics
        hosts = self.scan_data.get('hosts', [])
        total_hosts = len(hosts)
        critical_hosts = sum(1 for h in hosts if h.get('risk', 0) >= 60)
        high_risk = sum(1 for h in hosts if 40 <= h.get('risk', 0) < 60)

        summary_text = f"""
        This report presents the findings from a comprehensive network security assessment
        conducted on {self.scan_data.get('timestamp', 'N/A')}. The scan covered
        {total_hosts} network host(s) and identified security risks across multiple categories.

        <b>Key Findings:</b>
        <br/>• Total Hosts Scanned: {total_hosts}
        <br/>• Critical Risk Hosts: {critical_hosts}
        <br/>• High Risk Hosts: {high_risk}
        <br/>• Medium/Low Risk: {total_hosts - critical_hosts - high_risk}
        """

        story.append(Paragraph(summary_text, self.styles['Normal']))
        story.append(Spacer(1, 12))

        return story

    def _create_network_overview(self) -> List:
        """Create network overview section."""
        story = []

        story.append(Paragraph("Network Overview", self.styles['Heading1']))
        story.append(Spacer(1, 12))

        # Create host summary table
        hosts = self.scan_data.get('hosts', [])[:20]  # Limit to 20 for readability

        table_data = [['IP Address', 'Hostname', 'Device Type', 'Risk']]

        for host in hosts:
            ip = host.get('ip', 'N/A')
            hostname = host.get('hostname', 'Unknown')
            devtype = host.get('devtype', 'Unknown')
            risk = host.get('risk', 0)

            risk_text = f"{risk}/100"

            table_data.append([ip, hostname, devtype, risk_text])

        table = Table(table_data, colWidths=[1.5*inch, 2*inch, 1.5*inch, 1*inch])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 10),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))

        story.append(table)
        story.append(Spacer(1, 12))

        return story

    def _create_risk_analysis(self) -> List:
        """Create risk analysis section."""
        story = []

        story.append(Paragraph("Risk Analysis", self.styles['Heading1']))
        story.append(Spacer(1, 12))

        # Count risks by category
        hosts = self.scan_data.get('hosts', [])
        critical = [h for h in hosts if h.get('risk', 0) >= 60]
        high = [h for h in hosts if 40 <= h.get('risk', 0) < 60]
        medium = [h for h in hosts if 20 <= h.get('risk', 0) < 40]
        low = [h for h in hosts if h.get('risk', 0) < 20]

        # Risk distribution summary
        risk_summary = f"""
        <b>Risk Distribution:</b>
        <br/>• Critical (60-100): {len(critical)} host(s)
        <br/>• High (40-59): {len(high)} host(s)
        <br/>• Medium (20-39): {len(medium)} host(s)
        <br/>• Low (0-19): {len(low)} host(s)
        """
        story.append(Paragraph(risk_summary, self.styles['Normal']))
        story.append(Spacer(1, 12))

        # Critical risk hosts
        if critical:
            story.append(Paragraph(f"<b>Critical Risk Hosts ({len(critical)}):</b>", self.styles['Heading2']))
            story.append(Spacer(1, 6))

            for host in critical[:10]:
                ip = host.get('ip', 'N/A')
                risk = host.get('risk', 0)
                flags = host.get('flags', [])
                ports = host.get('ports', [])

                risk_text = f"""
                <font color="red"><b>{ip}</b></font> - Risk Score: {risk}/100
                <br/><b>Flags:</b> {', '.join(flags) if flags else 'None'}
                <br/><b>Open Ports:</b> {len(ports)} port(s) - {', '.join([str(p.get('port', '?')) for p in ports[:10]])}
                """

                # Add geolocation if available
                geo = host.get('geolocation', {})
                if geo and not geo.get('error'):
                    location = f"{geo.get('city', 'Unknown')}, {geo.get('country', 'Unknown')}"
                    risk_text += f"<br/><b>Location:</b> {location}"

                # Add threat intel if available
                threat = host.get('threat_intel', {})
                if threat and threat.get('is_malicious'):
                    risk_text += f"<br/><font color='red'><b>⚠ THREAT DETECTED:</b> Risk Level {threat.get('overall_risk', 'Unknown')}</font>"

                risk_text += "<br/>"
                story.append(Paragraph(risk_text, self.styles['Normal']))
                story.append(Spacer(1, 6))
        else:
            story.append(Paragraph("<i>No critical risk hosts detected.</i>", self.styles['Normal']))
            story.append(Spacer(1, 6))

        # High risk hosts (brief)
        if high:
            story.append(Paragraph(f"<b>High Risk Hosts ({len(high)}):</b>", self.styles['Heading2']))
            story.append(Spacer(1, 6))

            for host in high[:5]:
                ip = host.get('ip', 'N/A')
                risk = host.get('risk', 0)
                ports = host.get('ports', [])
                story.append(Paragraph(f"• <b>{ip}</b> - Risk: {risk}/100, Ports: {len(ports)}", self.styles['Normal']))

            if len(high) > 5:
                story.append(Paragraph(f"<i>...and {len(high) - 5} more</i>", self.styles['Normal']))
            story.append(Spacer(1, 6))

        return story

    def _create_vulnerability_findings(self) -> List:
        """Create vulnerability findings section."""
        story = []

        story.append(Paragraph("Vulnerability Findings", self.styles['Heading1']))
        story.append(Spacer(1, 12))

        hosts = self.scan_data.get('hosts', [])

        # Port/Service Details
        story.append(Paragraph("<b>Open Ports and Services:</b>", self.styles['Heading2']))
        story.append(Spacer(1, 6))

        hosts_with_ports = [h for h in hosts if h.get('ports')]
        if hosts_with_ports:
            for host in hosts_with_ports[:10]:  # Limit to 10 hosts
                ip = host.get('ip', 'N/A')
                ports = host.get('ports', [])

                port_summary = f"<b>{ip}</b> - {len(ports)} open port(s):"
                story.append(Paragraph(port_summary, self.styles['Normal']))

                # Show port details
                for port in ports[:15]:  # Limit to 15 ports per host
                    port_num = port.get('port', '?')
                    service = port.get('service', 'unknown')
                    version = port.get('version', '')
                    state = port.get('state', 'open')

                    port_detail = f"  • Port {port_num}/{port.get('protocol', 'tcp')} - {service}"
                    if version:
                        port_detail += f" ({version})"
                    port_detail += f" [{state}]"

                    story.append(Paragraph(port_detail, self.styles['Normal']))

                if len(ports) > 15:
                    story.append(Paragraph(f"  <i>...and {len(ports) - 15} more ports</i>", self.styles['Normal']))

                story.append(Spacer(1, 6))
        else:
            story.append(Paragraph("<i>No open ports detected or scan did not include port scanning.</i>", self.styles['Normal']))
            story.append(Spacer(1, 6))

        # CVE Vulnerabilities
        story.append(Paragraph("<b>CVE Vulnerabilities:</b>", self.styles['Heading2']))
        story.append(Spacer(1, 6))

        hosts_with_cves = [h for h in hosts if h.get('cves')]

        if hosts_with_cves:
            total_cves = sum(len(h.get('cves', [])) for h in hosts_with_cves)
            story.append(Paragraph(f"<font color='red'>Found {total_cves} CVE vulnerabilities across {len(hosts_with_cves)} host(s)</font>", self.styles['Normal']))
            story.append(Spacer(1, 6))

            for host in hosts_with_cves[:10]:
                ip = host.get('ip', 'N/A')
                cves = host.get('cves', [])
                story.append(Paragraph(f"<b>{ip}</b> - {len(cves)} CVE(s)", self.styles['Heading2']))

                for cve_finding in cves[:10]:  # Show first 10 CVEs per host
                    # Extract CVE details
                    service = cve_finding.get('service', 'Unknown')
                    port = cve_finding.get('port', '?')
                    cve_list = cve_finding.get('cves', [])

                    story.append(Paragraph(f"  Service: {service} (Port {port})", self.styles['Normal']))

                    for cve in cve_list[:5]:  # Show first 5 CVEs per service
                        cve_id = cve.get('cve_id', 'N/A')
                        severity = cve.get('severity', 'UNKNOWN')
                        cvss = cve.get('cvss_score', 'N/A')
                        description = cve.get('description', 'No description available')[:200]

                        cve_color = 'red' if severity in ['CRITICAL', 'HIGH'] else 'orange' if severity == 'MEDIUM' else 'black'

                        cve_text = f"""
                        <font color='{cve_color}'><b>{cve_id}</b></font> - Severity: {severity} (CVSS: {cvss})
                        <br/>{description}...
                        """
                        story.append(Paragraph(cve_text, self.styles['Normal']))

                story.append(Spacer(1, 6))

            if len(hosts_with_cves) > 10:
                story.append(Paragraph(f"<i>...and {len(hosts_with_cves) - 10} more hosts with CVEs</i>", self.styles['Normal']))
        else:
            story.append(Paragraph("<i>No CVE vulnerabilities detected or CVE scanning was not enabled (use --cve-check).</i>", self.styles['Normal']))

        story.append(Spacer(1, 12))

        # Exploit Information
        hosts_with_exploits = [h for h in hosts if h.get('exploits')]
        if hosts_with_exploits:
            story.append(Paragraph("<b>Available Exploits:</b>", self.styles['Heading2']))
            story.append(Spacer(1, 6))

            for host in hosts_with_exploits[:5]:
                ip = host.get('ip', 'N/A')
                exploits = host.get('exploits', [])

                story.append(Paragraph(f"<b>{ip}</b> - {len(exploits)} exploit(s) available", self.styles['Normal']))

                for exploit_data in exploits[:10]:
                    cve_id = exploit_data.get('cve_id', 'Unknown')
                    exploit_list = exploit_data.get('exploits', [])

                    if exploit_list:
                        story.append(Paragraph(f"  <font color='red'>{cve_id}</font>: {len(exploit_list)} exploit(s)", self.styles['Normal']))

                        for exp in exploit_list[:3]:
                            source = exp.get('source', 'Unknown')
                            title = exp.get('title', 'No title')
                            story.append(Paragraph(f"    • [{source}] {title}", self.styles['Normal']))

                story.append(Spacer(1, 6))

        return story

    def _create_tls_audit_section(self) -> List:
        """Create TLS/SSL audit section."""
        story = []

        story.append(Paragraph("TLS/SSL Security Audit", self.styles['Heading1']))
        story.append(Spacer(1, 12))

        hosts = self.scan_data.get('hosts', [])
        hosts_with_tls = [h for h in hosts if h.get('tls_audits')]

        if hosts_with_tls:
            story.append(Paragraph(f"<b>TLS/SSL security audits performed on {len(hosts_with_tls)} host(s):</b>", self.styles['Normal']))
            story.append(Spacer(1, 6))

            for host in hosts_with_tls[:10]:
                ip = host.get('ip', 'N/A')
                tls_audits = host.get('tls_audits', [])

                for audit in tls_audits:
                    port = audit.get('port', '?')
                    grade = audit.get('grade', 'F')
                    score = audit.get('score', 0)
                    protocols = audit.get('supported_protocols', [])
                    ciphers = audit.get('cipher_suites', [])

                    grade_color = 'green' if grade in ['A', 'A+'] else 'orange' if grade == 'B' else 'red'

                    tls_text = f"""
                    <b>{ip}:{port}</b> - Grade: <font color='{grade_color}'><b>{grade}</b></font> (Score: {score}/100)
                    <br/>Protocols: {', '.join(protocols) if protocols else 'None detected'}
                    <br/>Cipher Suites: {len(ciphers)} detected
                    """

                    issues = audit.get('security_issues', [])
                    if issues:
                        tls_text += f"<br/><font color='red'>Issues: {', '.join(issues[:5])}</font>"

                    story.append(Paragraph(tls_text, self.styles['Normal']))
                    story.append(Spacer(1, 6))
        else:
            story.append(Paragraph("<i>No TLS/SSL audits performed (use --tls-audit to enable).</i>", self.styles['Normal']))

        story.append(Spacer(1, 12))
        return story

    def _create_threat_intel_section(self) -> List:
        """Create threat intelligence section."""
        story = []

        story.append(Paragraph("Threat Intelligence", self.styles['Heading1']))
        story.append(Spacer(1, 12))

        hosts = self.scan_data.get('hosts', [])
        hosts_with_threats = [h for h in hosts if h.get('threat_intel', {}).get('is_malicious')]

        if hosts_with_threats:
            story.append(Paragraph(f"<font color='red'><b>⚠ WARNING: {len(hosts_with_threats)} malicious host(s) detected!</b></font>", self.styles['Normal']))
            story.append(Spacer(1, 6))

            for host in hosts_with_threats:
                ip = host.get('ip', 'N/A')
                threat = host.get('threat_intel', {})
                risk = threat.get('overall_risk', 'Unknown')
                sources = threat.get('threat_sources', [])

                threat_text = f"""
                <font color='red'><b>{ip}</b></font> - Risk Level: {risk}
                <br/>Detected by: {', '.join(sources) if sources else 'Unknown sources'}
                """

                # Add AbuseIPDB info
                abuseipdb = threat.get('abuseipdb', {})
                if abuseipdb:
                    confidence = abuseipdb.get('abuseConfidenceScore', 0)
                    reports = abuseipdb.get('totalReports', 0)
                    threat_text += f"<br/>AbuseIPDB: {confidence}% confidence ({reports} reports)"

                story.append(Paragraph(threat_text, self.styles['Normal']))
                story.append(Spacer(1, 6))
        else:
            story.append(Paragraph("<i>No malicious hosts detected via threat intelligence (use --threat-intel to enable).</i>", self.styles['Normal']))

        story.append(Spacer(1, 12))
        return story

    def _create_traffic_analysis_section(self) -> List:
        """Create traffic analysis section."""
        story = []

        story.append(Paragraph("Traffic Analysis", self.styles['Heading1']))
        story.append(Spacer(1, 12))

        # Check if any host has traffic analysis data
        hosts = self.scan_data.get('hosts', [])
        traffic_data = None

        for host in hosts:
            if host.get('traffic_analysis'):
                traffic_data = host.get('traffic_analysis')
                break

        if traffic_data:
            stats = traffic_data.get('statistics', {})
            creds = traffic_data.get('credentials', [])
            files = traffic_data.get('files', [])
            warnings = traffic_data.get('warnings', [])

            # Statistics
            story.append(Paragraph(f"<b>Packet Capture Statistics:</b>", self.styles['Heading2']))
            story.append(Paragraph(f"Total Packets: {stats.get('total_packets', 0):,}", self.styles['Normal']))
            story.append(Paragraph(f"Total Bytes: {stats.get('total_bytes', 0):,}", self.styles['Normal']))
            story.append(Spacer(1, 6))

            # Credentials found
            if creds:
                story.append(Paragraph(f"<font color='red'><b>⚠ {len(creds)} Credential(s) Found in Unencrypted Traffic!</b></font>", self.styles['Heading2']))
                for cred in creds[:10]:
                    protocol = cred.get('protocol', 'Unknown')
                    src = cred.get('src_ip', 'Unknown')
                    dst = cred.get('dst_ip', 'Unknown')

                    cred_text = f"[{protocol}] {src} → {dst}"
                    if 'username' in cred and 'password' in cred:
                        cred_text += f"<br/>  Username: <font face='Courier'>{cred['username']}</font>"
                        cred_text += f"<br/>  Password: <font face='Courier'>{cred['password']}</font>"

                    story.append(Paragraph(cred_text, self.styles['Normal']))
                    story.append(Spacer(1, 4))
            else:
                story.append(Paragraph("✓ No credentials found in unencrypted traffic.", self.styles['Normal']))

            story.append(Spacer(1, 6))

            # Files carved
            if files:
                story.append(Paragraph(f"<b>{len(files)} File(s) Carved from Traffic:</b>", self.styles['Heading2']))
                for file_info in files[:10]:
                    file_type = file_info.get('type', 'Unknown')
                    size = file_info.get('size_bytes', 0)
                    md5 = file_info.get('md5', 'N/A')
                    story.append(Paragraph(f"• {file_type} ({size:,} bytes) - MD5: {md5}", self.styles['Normal']))
                story.append(Spacer(1, 6))

            # Security warnings
            if warnings:
                story.append(Paragraph(f"<b>Security Warnings ({len(warnings)}):</b>", self.styles['Heading2']))
                for warning in warnings:
                    severity = warning.get('severity', 'UNKNOWN')
                    issue = warning.get('issue', 'Unknown issue')
                    color = 'red' if severity == 'HIGH' else 'orange'
                    story.append(Paragraph(f"<font color='{color}'>[{severity}] {issue}</font>", self.styles['Normal']))
                story.append(Spacer(1, 6))
        else:
            story.append(Paragraph("<i>No traffic analysis data available (use --capture --analyze-traffic to enable).</i>", self.styles['Normal']))

        story.append(Spacer(1, 12))
        return story

    def _create_recommendations(self) -> List:
        """Create recommendations section."""
        story = []

        story.append(Paragraph("Recommendations", self.styles['Heading1']))
        story.append(Spacer(1, 12))

        recommendations = [
            "1. Address all critical risk hosts immediately (risk ≥ 60)",
            "2. Update systems with known CVE vulnerabilities",
            "3. Disable deprecated protocols (Telnet, FTP, unencrypted HTTP)",
            "4. Implement network segmentation for high-risk devices",
            "5. Conduct regular security scans (recommended: weekly)"
        ]

        for rec in recommendations:
            story.append(Paragraph(rec, self.styles['Normal']))
            story.append(Spacer(1, 6))

        return story


def generate_pdf_report(scan_data: Dict[str, Any], output_file: str, report_format: str = 'professional'):
    """
    Convenience function to generate PDF report.

    Args:
        scan_data: Scan results dictionary
        output_file: Output PDF file path
        report_format: Report format (executive, professional, technical)
    """
    report = ProfessionalReport(scan_data, report_format)
    report.generate(output_file)
